#!/bin/bash -v

chmod -R 644 ../
TARGET_DIR=/var/lib/home639server/
mkdir $TARGET_DIR
cp ../* $TARGET_DIR

SETTINGS_FILE=../HomeServerSettings.json
if [ -f $SETTINGS_FILE ]
then
	cp $SETTINGS_FILE /etc/
fi

cp home639server.service /etc/systemd/system/
systemctl daemon-reload
#systemctl enable home639server.service