//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeModbus.Models.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLog
    {
        public int Id { get; set; }
        public string ParameterId { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<long> IntValue { get; set; }
        public Nullable<double> DoubleValue { get; set; }
        public Nullable<bool> BoolValue { get; set; }
        public string StringValue { get; set; }
        public byte[] BlobValue { get; set; }
    }
}
